language: node_js
node_js:
- '4.4'
script: gulp build
deploy:
  provider: heroku
  on: deploy
  skip_cleanup: true
  api_key:
    secure: "RYjMottjGYz9VOsN8j2C0sr8CNK4uJ1HpU1RhDVJAbdH/+ClHtgc75ctZXSpz6xyxvNQtg0vzZdfHzAsMgOpU/g/Gn9+A0t1S2GoDoqeAKGwFOas4xmAwC0Fq5zE8W5vl3rqYncAmBW24s2x5pxPoLdNpkPu4du5CX4d8easnc3MdOwqneoKRGGdcSwDDfojiGJs/d3reIz+gR7NMjJUcPOiTYB3qQ0kV7I8+0n1pG+84mamHnZ/71VtiP1CeClkiOEr8ObxPwTWlJ6ZsYRgypmnVCLZnhOaFONyOfloyQ128zKmZ+QDEjNYGSP/xQqKoyHG+cWSygs2h+fN6oIXNwIAQQhvhQOtSnPuyRcOLuD6Lv7J5No8WnT1LF8CKUXVG1ivqk2SR0/fx9egbiwJO62xn0qLCdEb9JWTyt0Xxgc9ecogGd0p3iLKkSHlA7bnRnicpQvCM1d72jyDvSfDw3tcRAMAP+T4+nhuHNO38Jhjp9OoLosZs/o285eg2xK0xa80684PtpuZnGSr9RVdYOIpghJD26+OD4DfBGcSWzNqFv7Ot8IamhxdY+FNPY4b9BZPP5USY+j7IPdUEdqI/cNEwcysru9jzPN4fBVzzbAcpklyNsOJOvV61MlwYsnvMMRwBAKjLhWuTd6WAQZzb3PZ7WMad5SQvCiOiZR72x8="